### ISSUE TITLE
How to run your programme

### ISSUE THREAD

**Issue by Vansir01** [TommyClausner/knit-portrait#1]
I tried to run it in Spyder Ipython,but failed. Where should I input my own picture? And how to use the interactive console to run the code? Please help me,THX!

Traceback (most recent call last):

  File "<ipython-input-1-0ab7a3de6731>", line 1, in <module>
    runfile('D:/google downloads/knit-portrait-master/knit-portrait-master/display_result.py', wdir='D:/google downloads/knit-portrait-master/knit-portrait-master')

  File "D:\Annoconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Annoconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/google downloads/knit-portrait-master/knit-portrait-master/display_result.py", line 47, in <module>
    main()

  File "D:/google downloads/knit-portrait-master/knit-portrait-master/display_result.py", line 15, in main
    args = parser.parse_args()

  File "D:\Annoconda\lib\argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)

  File "D:\Annoconda\lib\argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)

  File "D:\Annoconda\lib\argparse.py", line 2016, in _parse_known_args
    ', '.join(required_actions))

  File "D:\Annoconda\lib\argparse.py", line 2501, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

  File "D:\Annoconda\lib\argparse.py", line 2488, in exit
    _sys.exit(status)

SystemExit: 2

**Comment by TommyClausner** [comment]
The program is meant to by run from some terminal / command line application like so:
`python compute_string_order.py -f <path/to/your/image.jpg> -sa <path/to/your/outputfile>  -d 0.3 -nd 15`

Note that "image.jpg" has an extension, whereas "outputfile" has no file extension. `-d` refers to the contrast discount used to compute the result (need to play around with this value between 0 and 1 a bit) and `-nd` is the minimum distance between "hooks" that the algorithm is allowed to choose.

Once the above was computed you can run:
`python display_result.py <path/to/your/outputfile.json> -st <number of strings>` in a command line to display the result. `-st` is the number of strings to be displayed, which must be less or equal to what was computed above. Since the default is 5000 for the computation, maybe 3000 would be a sensible number.

What went wrong in your case is that you tried to run the program as is as a script. So the argument parser crashes because it expects some arguments. So the easiest indeed is to take a command line application (like "terminal" in linux or mac os or the windows "command line" application). And run as described in the readme.

If you however want to run it as a script inside a jupyter notebook or so , you might want to open `compute_string_order.py` and copy all functions in `main` below the argument parser into a new script, fill the arguments yourself and you should be good to go (same with the displaying program). E.g.:

```
file = 'your/image.jpg'
size = 2500
crop_factor = 1
hooks = 201
strings = 5000
discount = 0.3
neighbor_distance = 15
random_accept_rate = 0
save_as = 'your/outputfile'

config = {'image': {'file': file, 'size': size, 'crop_factor': crop_factor},
              'settings': {'hooks':hooks, 'strings':strings, 'discount':discount,
                           'distance':neighbor_distance, 'random_accept':random_accept_rate,
                           'save_file': save_as}}

ref_img = pre_proc_img(file, size, crop_factor)
circle = make_circle(ref_img, num_hooks=hooks)

string_order = fit_strings(
    ref_img,
    circle,
    hook_dist=neighbor_distance,
    discount=discount,
    num_strings=strings,
    random_accept=random_accept_rate)

save_string_order(string_order, filename=save_as + '.csv')

save_config(config, filename=save_as + '.json')```

**Comment by Vansir01** [comment]
Yeah,that's really useful. And actually I can run the 【compute_string_order.py】successfully wherever in the commad line or in the script. And it turned out to be a csv and a json file. However,the 【display_result.py 】failed. Are there any solutions to run it in script either? (Because when I tried to runn it in cmd,it always had some module related error...

**Comment by Vansir01** [comment]
Oh,I solved the problem! Thank you very much.

import matplotlib.pylab as plt
from knit_portrait.IO import load_string_order, load_config
from knit_portrait.image_processing import pre_proc_img, make_circle
num_strings = 100
file ='zyq.json'
config = load_config(filename=file)
string_order = load_string_order(filename=config['settings']['save_file'] + '.csv')[:, 1:]

#    if args.strings == -1:
#        num_strings = config['settings']['strings']
#    else:
#        num_strings = args.strings

ref_img = pre_proc_img(config['image']['file'], config['image']['size'], 1)
circle = make_circle(ref_img, num_hooks=config['settings']['hooks'])

plt.figure(figsize=(16, 9))
plt.subplot(121)
plt.imshow(ref_img, 'gray')
plt.axis('off')

plt.subplot(122)
for string_pair in string_order[:num_strings, :]:
    plt.plot([circle[string_pair[0], 1], circle[string_pair[1], 1]],
             [circle[string_pair[0], 0], circle[string_pair[1], 0]], 'black', LineWidth=0.05)
    plt.gca()

plt.axis('equal')
plt.axis('off')
plt.gca().invert_yaxis()
plt.savefig(config['settings']['save_file'] + '_result.jpg')
plt.show()

**Comment by Vansir01** [comment]
Oh,I solved the problem! Thank you very much.

import matplotlib.pylab as plt
from knit_portrait.IO import load_string_order, load_config
from knit_portrait.image_processing import pre_proc_img, make_circle
num_strings = 100
file ='zyq.json'
config = load_config(filename=file)
string_order = load_string_order(filename=config['settings']['save_file'] + '.csv')[:, 1:]

if args.strings == -1:
num_strings = config['settings']['strings']
else:
num_strings = args.strings
ref_img = pre_proc_img(config['image']['file'], config['image']['size'], 1)
circle = make_circle(ref_img, num_hooks=config['settings']['hooks'])

plt.figure(figsize=(16, 9))
plt.subplot(121)
plt.imshow(ref_img, 'gray')
plt.axis('off')

plt.subplot(122)
for string_pair in string_order[:num_strings, :]:
plt.plot([circle[string_pair[0], 1], circle[string_pair[1], 1]],
[circle[string_pair[0], 0], circle[string_pair[1], 0]], 'black', LineWidth=0.05)
plt.gca()

plt.axis('equal')
plt.axis('off')
plt.gca().invert_yaxis()
plt.savefig(config['settings']['save_file'] + '_result.jpg')
plt.show()

**Comment by Vansir01** [comment]
And by the way, did you think about adding something like color into your code? That might be more interesting uhh!

**Comment by TommyClausner** [comment]
Cool ! Thanks for the update ! Hope the results are as you expected :)

Color would indeed be a nice additive, however I personally like the grayscale more anyway. And it's actually not as straight forward as it might seem. But I'll consider it for the future.
